<?php

/*
| Module manifest: read by App\Platform\Modules\ModuleRegistry.
| Business numbers never live here; they are rules (Rules::get('attendance.*')).
*/

use Modules\Attendance\Dashboard\CheckedInToday;
use Modules\Attendance\Dashboard\CorrectionsWaiting;
use Modules\Attendance\Offline\PunchSync;

return [
    'key' => 'attendance',
    'name' => 'attendance::module.name',
    'description' => 'attendance::module.description',
    'version' => '1.0.0',
    'category' => 'business',
    // Employees are HRM's (read through Modules\Hrm\Directory\EmployeeDirectory).
    'requires' => ['hrm'],
    'sectors' => ['*'],
    'plans' => ['*'],
    'permissions' => [
        'attendance.view',
        // Shifts, holidays, rosters; punches written or voided by hand; corrections for someone.
        'attendance.manage',
        // Check in and out for oneself, and ask to fix one's own day.
        'attendance.punch',
        // Approve or reject corrections (never one's own).
        'attendance.correct',
    ],
    'rules' => [
        [
            'key' => 'attendance.late_grace_minutes',
            'type' => 'integer',
            'schema' => ['minimum' => 0, 'maximum' => 240],
            'default' => 10,
            'label' => 'attendance::rules.late_grace_minutes.label',
            'description' => 'attendance::rules.late_grace_minutes.description',
            'overridable_levels' => ['platform', 'partner', 'plan', 'group', 'company', 'branch', 'department'],
            'category' => 'lateness',
            'sort_order' => 10,
        ],
        [
            'key' => 'attendance.weekend_days',
            'type' => 'multi_enum',
            'schema' => ['items' => ['enum' => ['sat', 'sun', 'mon', 'tue', 'wed', 'thu', 'fri']], 'maxItems' => 3],
            // Country values (e.g. BD) are data, seeded per country.
            'default' => ['sat', 'sun'],
            'label' => 'attendance::rules.weekend_days.label',
            'description' => 'attendance::rules.weekend_days.description',
            'overridable_levels' => ['platform', 'partner', 'group', 'company', 'branch'],
            'country_specific' => true,
            'category' => 'calendar',
            'sort_order' => 20,
        ],
        [
            'key' => 'attendance.half_day_after_minutes',
            'type' => 'integer',
            'schema' => ['minimum' => 0, 'maximum' => 720],
            'default' => 240,
            'label' => 'attendance::rules.half_day_after_minutes.label',
            'description' => 'attendance::rules.half_day_after_minutes.description',
            'overridable_levels' => ['platform', 'partner', 'group', 'company', 'branch', 'department'],
            'category' => 'lateness',
            'sort_order' => 30,
        ],
        [
            'key' => 'attendance.overtime_min_minutes',
            'type' => 'integer',
            'schema' => ['minimum' => 0, 'maximum' => 240],
            'default' => 30,
            'label' => 'attendance::rules.overtime_min_minutes.label',
            'description' => 'attendance::rules.overtime_min_minutes.description',
            'overridable_levels' => ['platform', 'partner', 'group', 'company', 'branch', 'department'],
            'country_specific' => true,
            'category' => 'lateness',
            'sort_order' => 35,
        ],
        [
            'key' => 'attendance.geo_fence_required',
            'type' => 'boolean',
            'default' => false,
            'label' => 'attendance::rules.geo_fence_required.label',
            'description' => 'attendance::rules.geo_fence_required.description',
            'overridable_levels' => ['platform', 'partner', 'group', 'company', 'branch', 'department'],
            'category' => 'check_in',
            'sort_order' => 40,
        ],
        [
            'key' => 'attendance.self_punch',
            'type' => 'boolean',
            'default' => true,
            'label' => 'attendance::rules.self_punch.label',
            'description' => 'attendance::rules.self_punch.description',
            'overridable_levels' => ['platform', 'partner', 'plan', 'group', 'company', 'branch', 'department'],
            'category' => 'check_in',
            'sort_order' => 45,
        ],
        [
            'key' => 'attendance.early_punch_minutes',
            'type' => 'integer',
            'schema' => ['minimum' => 30, 'maximum' => 600],
            'default' => 240,
            'label' => 'attendance::rules.early_punch_minutes.label',
            'description' => 'attendance::rules.early_punch_minutes.description',
            'overridable_levels' => ['platform', 'partner', 'group', 'company', 'branch'],
            'category' => 'check_in',
            'sort_order' => 50,
        ],
        [
            'key' => 'attendance.correction_max_days',
            'type' => 'integer',
            'schema' => ['minimum' => 0, 'maximum' => 366],
            'default' => 31,
            'label' => 'attendance::rules.correction_max_days.label',
            'description' => 'attendance::rules.correction_max_days.description',
            'overridable_levels' => ['platform', 'partner', 'plan', 'group', 'company', 'branch'],
            'sensitive' => true,
            'category' => 'corrections',
            'sort_order' => 60,
        ],
        [
            'key' => 'attendance.geo_radius_m',
            'type' => 'integer',
            'schema' => ['minimum' => 20, 'maximum' => 5000],
            'default' => 200,
            'label' => 'attendance::rules.geo_radius_m.label',
            'description' => 'attendance::rules.geo_radius_m.description',
            'overridable_levels' => ['platform', 'partner', 'group', 'company', 'branch', 'department'],
            'category' => 'check_in',
            'sort_order' => 41,
        ],
        [
            'key' => 'attendance.geo_max_accuracy_m',
            'type' => 'integer',
            'schema' => ['minimum' => 10, 'maximum' => 1000],
            'default' => 100,
            'label' => 'attendance::rules.geo_max_accuracy_m.label',
            'description' => 'attendance::rules.geo_max_accuracy_m.description',
            'overridable_levels' => ['platform', 'partner', 'group', 'company', 'branch', 'department'],
            'category' => 'check_in',
            'sort_order' => 42,
        ],
        [
            'key' => 'attendance.location_retention_days',
            'type' => 'integer',
            'schema' => ['minimum' => 1, 'maximum' => 3650],
            'default' => 90,
            'label' => 'attendance::rules.location_retention_days.label',
            'description' => 'attendance::rules.location_retention_days.description',
            'overridable_levels' => ['platform', 'partner', 'group', 'company'],
            'sensitive' => true,
            'category' => 'check_in',
            'sort_order' => 43,
        ],
        [
            'key' => 'attendance.offline_max_age_hours',
            'type' => 'integer',
            'schema' => ['minimum' => 1, 'maximum' => 720],
            'default' => 72,
            'label' => 'attendance::rules.offline_max_age_hours.label',
            'description' => 'attendance::rules.offline_max_age_hours.description',
            'overridable_levels' => ['platform', 'partner', 'group', 'company', 'branch'],
            'category' => 'check_in',
            'sort_order' => 46,
        ],
        [
            'key' => 'attendance.device_import_max_rows',
            'type' => 'integer',
            'schema' => ['minimum' => 100, 'maximum' => 100000],
            'default' => 20000,
            'label' => 'attendance::rules.device_import_max_rows.label',
            'description' => 'attendance::rules.device_import_max_rows.description',
            'overridable_levels' => ['platform', 'partner', 'plan'],
            'category' => 'devices',
            'sort_order' => 70,
        ],
        [
            'key' => 'attendance.device_import_max_kb',
            'type' => 'integer',
            'schema' => ['minimum' => 16, 'maximum' => 10240],
            'default' => 5120,
            'label' => 'attendance::rules.device_import_max_kb.label',
            'description' => 'attendance::rules.device_import_max_kb.description',
            'overridable_levels' => ['platform', 'partner', 'plan'],
            'category' => 'devices',
            'sort_order' => 71,
        ],
    ],
    'menu' => [
        [
            'key' => 'attendance',
            'label' => 'attendance::module.menu',
            'route' => '/attendance',
            'icon' => 'clock',
            'order' => 20,
            'section' => 'people',
            'children' => [
                ['key' => 'today', 'label' => 'attendance::module.menu_today', 'route' => '/attendance', 'permission' => 'attendance.view'],
                ['key' => 'me', 'label' => 'attendance::module.menu_me', 'route' => '/attendance/me', 'permission' => 'attendance.punch'],
                ['key' => 'month', 'label' => 'attendance::module.menu_month', 'route' => '/attendance/month', 'permission' => 'attendance.view'],
                ['key' => 'corrections', 'label' => 'attendance::module.menu_corrections', 'route' => '/attendance/corrections', 'permission' => 'attendance.view'],
            ],
        ],
    ],
    // The header "New" menu: checking in from anywhere.
    'quick_actions' => [
        ['key' => 'check_in', 'label' => 'attendance::module.check_in', 'route' => '/attendance/me', 'permission' => 'attendance.punch', 'icon' => 'clock'],
    ],
    'events' => [],
    'is_core' => false,
    'requires_consent' => false,
    'dashboard' => ['widgets' => [
        ['key' => 'checked_in', 'label' => 'attendance::dashboard.checked_in', 'type' => 'stat', 'provider' => CheckedInToday::class, 'permission' => 'attendance.view', 'overview' => true],
        ['key' => 'corrections', 'label' => 'attendance::dashboard.corrections', 'type' => 'stat', 'provider' => CorrectionsWaiting::class, 'permission' => 'attendance.view'],
    ]],
    'attention' => [CorrectionsWaiting::class],
    // Checking in while the phone is offline (Offline mode on).
    'sync_records' => [PunchSync::class],
    'settings' => ['pages' => [
        ['key' => 'shifts', 'label' => 'attendance::module.menu_shifts', 'route' => '/attendance/shifts', 'permission' => 'attendance.view'],
        ['key' => 'holidays', 'label' => 'attendance::module.menu_holidays', 'route' => '/attendance/holidays', 'permission' => 'attendance.view'],
        ['key' => 'rosters', 'label' => 'attendance::module.menu_rosters', 'route' => '/attendance/rosters', 'permission' => 'attendance.view'],
        ['key' => 'locations', 'label' => 'attendance::module.menu_locations', 'route' => '/attendance/locations', 'permission' => 'attendance.view'],
    ]],
    // An employee opens their own days from their record in the client's portal.
    'portal_pages' => [
        ['subject' => 'hrm.employee', 'label' => 'attendance::module.portal_days', 'route' => '/portal/attendance'],
    ],
];
