<?php

namespace App\Platform\Security;

use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Route as Router;

/**
 * Every HTTP endpoint with how it is protected (Phase 11), read from the
 * routes themselves: for the penetration-test scope (docs/security) and for
 * reviewers. Kept in step with the code by tests/Feature/Security/EndpointInventoryTest.
 */
class EndpointInventory
{
    /**
     * @return list<array{methods: string, uri: string, access: string, context: string, module: string, limits: string, step_up: bool}>
     */
    public function all(): array
    {
        $rows = [];

        foreach (Router::getRoutes() as $route) {
            /** @var Route $route */
            $middleware = array_map('strval', $route->gatherMiddleware());
            $has = fn (string ...$needles) => collect($middleware)->contains(fn (string $m) => collect($needles)->contains(fn (string $needle) => $m === $needle || str_starts_with($m, $needle.':') || str_ends_with($m, '\\'.$needle)));

            $rows[] = [
                'methods' => implode(', ', array_values(array_diff($route->methods(), ['HEAD']))),
                'uri' => '/'.ltrim($route->uri(), '/'),
                'access' => match (true) {
                    $has('partner.key', 'AuthenticatePartnerKey') => 'partner API key',
                    $has('auth', 'Authenticate') => 'signed in',
                    $has('signed', 'ValidateSignature') => 'signed link',
                    default => 'public',
                },
                'context' => match (true) {
                    $has('org', 'ResolveOrganization') => 'organization',
                    $has('partner', 'ResolvePartner') => 'partner console',
                    default => '',
                },
                'module' => collect($middleware)->filter(fn (string $m) => str_starts_with($m, 'module:'))->map(fn (string $m) => substr($m, 7))->implode(', '),
                'limits' => collect($middleware)
                    ->filter(fn (string $m) => str_starts_with($m, 'throttle:') || str_contains($m, 'ThrottleRequests:'))
                    ->map(fn (string $m) => substr($m, strrpos($m, ':') + 1))
                    ->implode(', '),
                'step_up' => $has('two_factor.recent', 'RequireRecentTwoFactor'),
            ];
        }

        usort($rows, fn (array $a, array $b) => [$a['uri'], $a['methods']] <=> [$b['uri'], $b['methods']]);

        return $rows;
    }

    /**
     * The inventory as a Markdown document, grouped by area.
     */
    public function markdown(): string
    {
        $rows = $this->all();
        $count = fn (string $access) => count(array_filter($rows, fn (array $row) => $row['access'] === $access));

        $out = "# Endpoint inventory\n\n"
            ."Generated by `php artisan security:endpoints --write` from the routes; do not edit by hand\n"
            ."(a test fails when this file and the code differ).\n\n"
            .count($rows).' endpoints: '.$count('public').' public, '.$count('signed in').' signed in, '
            .$count('partner API key').' partner API key, '.$count('signed link')." signed link.\n"
            ."Every /api endpoint also has the general per-address, per-person and per-organization limits.\n";

        $groups = [];
        foreach ($rows as $row) {
            $segments = explode('/', trim($row['uri'], '/'));
            $group = $segments[0] === 'api' ? '/api/'.($segments[1] ?? '') : '/'.$segments[0];
            $groups[$group][] = $row;
        }

        foreach ($groups as $group => $items) {
            $out .= "\n## {$group}\n\n| Method | Path | Access | Context | Module | Limits | Step-up |\n|---|---|---|---|---|---|---|\n";
            foreach ($items as $row) {
                $out .= "| {$row['methods']} | `{$row['uri']}` | {$row['access']} | {$row['context']} | {$row['module']} | {$row['limits']} | ".($row['step_up'] ? 'yes' : '')." |\n";
            }
        }

        return $out;
    }
}
